packages:
  - server
  - consumer-client
  - merchant-client
  - mobile-client
  - packages/*
allowBuilds:
  '@prisma/engines': true
  prisma: true
  sharp: true
  esbuild: true
  '@scarf/scarf': false
