services:
  # APPLICATION BACKEND (NEST)
  - type: web
    name: spotly-api
    env: node
    buildCommand: pnpm install && pnpm turbo run build --filter=@spotly/api
    startCommand: pnpm --filter @spotly/api start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PORT
        value: 3001
      - key: CONSUMER_URL
        value: https://spotly-consumer.onrender.com
      - key: MERCHANT_URL
        value: https://spotly-merchant.onrender.com

      # - FIREBASE_PROJECT_ID
      # - FIREBASE_CLIENT_EMAIL
      # - FIREBASE_PRIVATE_KEY

  # CONSUMER FRONTEND (NEXT)
  - type: web
    name: spotly-consumer
    env: node
    buildCommand: pnpm install && pnpm turbo run build --filter=@spotly/consumer
    startCommand: pnpm --filter @spotly/consumer start -p $PORT
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NEXT_PUBLIC_API_URL
        value: https://spotly-api.onrender.com/api
      - key: NEXT_PUBLIC_WS_URL
        value: https://spotly-api.onrender.com
      # Firebase Client Keys
      - key: NEXT_PUBLIC_FIREBASE_API_KEY
        value: placeholder_key_see_render_dashboard
      - key: NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
        value: spotly-d321e.firebaseapp.com
      - key: NEXT_PUBLIC_FIREBASE_PROJECT_ID
        value: spotly-d321e
      - key: NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
        value: spotly-d321e.firebasestorage.app
      - key: NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
        value: 787801999813
      - key: NEXT_PUBLIC_FIREBASE_APP_ID
        value: 1:787801999813:web:b158230a580e9a159563ac

  # MERCHANT FRONTEND (NEXT)
  - type: web
    name: spotly-merchant
    env: node
    buildCommand: pnpm install && pnpm turbo run build --filter=@spotly/merchant
    startCommand: pnpm --filter @spotly/merchant start -p $PORT
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NEXT_PUBLIC_API_URL
        value: https://spotly-api.onrender.com/api
      - key: NEXT_PUBLIC_WS_URL
        value: https://spotly-api.onrender.com
      - key: NEXT_PUBLIC_FIREBASE_API_KEY
        value: placeholder_key_see_render_dashboard
      - key: NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
        value: spotly-d321e.firebaseapp.com
      - key: NEXT_PUBLIC_FIREBASE_PROJECT_ID
        value: spotly-d321e
      - key: NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
        value: spotly-d321e.firebasestorage.app
      - key: NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
        value: 787801999813
      - key: NEXT_PUBLIC_FIREBASE_APP_ID
        value: 1:787801999813:web:b158230a580e9a159563ac
