import React from 'react';
import { THEME } from '@spotly/ui';

export const s = {
  ...THEME.styles,
  input: {
    padding: '14px 16px',
    borderRadius: 16,
    background: 'rgba(255,255,255,.03)',
    border: '1px solid rgba(255,255,255,.08)',
    color: '#fff',
    outline: 'none',
    transition: 'all .3s cubic-bezier(0.4, 0, 0.2, 1)',
    width: '100%',
    fontSize: 15,
    fontFamily: 'var(--font-sans)',
  } as React.CSSProperties,
  btnC: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    padding: '14px 28px',
    borderRadius: 14,
    background: THEME.gradients.consumer,
    color: '#000',
    fontWeight: 800,
    fontSize: 15,
    border: 'none',
    cursor: 'pointer',
    transition: 'all .25s ease',
    boxShadow: '0 8px 24px rgba(245,196,24,.2)',
  } as React.CSSProperties,
  card: {
    ...THEME.styles.card,
    background: 'rgba(255,255,255,.01)',
    backdropFilter: 'blur(12px)',
    border: '1px solid rgba(255,255,255,.06)',
    borderRadius: 20,
    padding: '18px',
    transition: 'all .3s ease',
  } as React.CSSProperties,
  categoryBtn: {
    whiteSpace: 'nowrap',
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    padding: '10px 22px',
    borderRadius: 999,
    border: '1px solid rgba(255,255,255,.06)',
    background: 'rgba(255,255,255,.03)',
    color: 'rgba(255,255,255,.6)',
    fontWeight: 700,
    fontSize: 14,
    cursor: 'pointer',
    transition: 'all .25s ease',
  } as React.CSSProperties,
  gradC: { background: THEME.gradients.consumer } as React.CSSProperties,
  gradCText: THEME.gradients.consumerText,
  badge: THEME.badge,
};
